CREATE TABLE roles (
   role_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
   role_name VARCHAR(255) UNIQUE NOT NULL,
   created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
